# Project information
site_name: '复旦大学腾飞书院先导课程'
site_description: '复旦大学腾飞书院先导课程——程序设计'
site_author: '程序设计课程设计工作组'
site_url: 'https://zfhu.ac.cn/Prior-Course-Fudan'
site_dir: 'docs'
docs_dir: 'content'
edit_uri: 'edit/master/content'

# Repository
repo_name: 'ichn-hu/Prior-Course-Fudan'
repo_url: 'https://github.com/ichn-hu/Prior-Course-Fudan'

# Copyright
copyright: 'Built by <a href="http://github.com/ichn-hu">ichn-hu</a> &copy; 2020'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'custom/'
  favicon: '/static/assets/fudan.svg'
  palette:
    primary: 'Black'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: material/cloud
  feature:
    - tabs

# # Customization
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/ichn-hu'

extra_css:
  - 'static/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css'

extra_javascript:
  - 'static/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/auto-render.min.js'

# Google Analytics
google_analytics:
  - 'UA-149024530-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# nav:
#   - 程序设计课程主页: index.md
  